name: Git repo checkout
on: workflow_dispatch
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: checkout
       uses: actions/checkout@v4
     - name: print content
       run: cat index.html

     
