name: if demo
on: push
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run if branch is main
        if: github.ref == 'refs/heads/main'
        run: echo " this is if demo"
      - name: run this step
        run: echo " this is without condition"
