name: if demo
on: push
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run krishna or kuchalakanti
        if: github.actor == 'kuchalakanti'
        run: echo " It is triggered by kuchalakanti"
